### ISSUE TITLE
Make an installation procedure.

### ISSUE THREAD

**Issue by mathieulavoie** [mathieulavoie/Bitcluster#1]
Do an installation procedure to get Bitcluster run on your own machine.

**Comment by pshenmic** [comment]
+1

After installation dependencies:

C:\Users\test\Downloads\Bitcluster-master>start_webapi.py
Traceback (most recent call last):
  File "C:\Users\test\Downloads\Bitcluster-master\start_webapi.py", line 1, in <module>
    from web.api import app
  File "C:\Users\test\Downloads\Bitcluster-master\web\api.py", line 3, in <module>
    from web.dao import getNodeFromAddress, getNodeInformation, getTransations,
groupByAllDistribution, groupbyNode,
  File "C:\Users\test\Downloads\Bitcluster-master\web\web.py", line 2, in <module>
    from web.dao import getNodeFromAddress, getNodeInformation, getTransations,
groupByAllDistribution, groupbyNode, 
ImportError: No module named dao

I'm developer, but not familiar with python

**Comment by mathieulavoie** [comment]
@pshenmic You need Python 3 to run the projet. I will add it in the requirements. I did got the exact same issue as you when I did run it with Python 2.7.

**Comment by pshenmic** [comment]
C:\Users\test\Downloads\Bitcluster-master>py start_website.py
- Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
  127.0.0.1 - - [26/Jul/2016 13:44:47] "GET / HTTP/1.1" 200 -
  127.0.0.1 - - [26/Jul/2016 13:45:31] "GET / HTTP/1.1" 200 -
  [2016-07-26 13:45:50,936] ERROR in app: Exception on / [POST]
  Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python35-32\lib\site-packages
  \flask\app.py", line 1988, in wsgi_app
  response = self.full_dispatch_request()
  File "C:\Users\test\AppData\Local\Programs\Python\Python35-32\lib\site-packages
  \flask\app.py", line 1641, in full_dispatch_request
  rv = self.handle_user_exception(e)
  File "C:\Users\test\AppData\Local\Programs\Python\Python35-32\lib\site-packages
  \flask\app.py", line 1544, in handle_user_exception
  reraise(exc_type, exc_value, tb)
  File "C:\Users\test\AppData\Local\Programs\Python\Python35-32\lib\site-packages
  \flask_compat.py", line 33, in reraise
  raise value
  File "C:\Users\test\AppData\Local\Programs\Python\Python35-32\lib\site-packages
  \flask\app.py", line 1639, in full_dispatch_request
  rv = self.dispatch_request()
  File "C:\Users\test\AppData\Local\Programs\Python\Python35-32\lib\site-packages
  \flask\app.py", line 1625, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\test\Downloads\Bitcluster-master\web\web.py", line 26, in web_ro
  ot
  node_id = getNodeFromAddress(address)
  File "C:\Users\test\Downloads\Bitcluster-master\web\dao.py", line 10, in getNod
  eFromAddress
  cursor = db.addresses.find_one({"_id": address})
  File "C:\Users\test\AppData\Local\Programs\Python\Python35-32\lib\site-packages
  \pymongo\collection.py", line 1014, in find_one
  for result in cursor.limit(-1):
  File "C:\Users\test\AppData\Local\Programs\Python\Python35-32\lib\site-packages
  \pymongo\cursor.py", line 1090, in next
  if len(self.__data) or self._refresh():
  File "C:\Users\test\AppData\Local\Programs\Python\Python35-32\lib\site-packages
  \pymongo\cursor.py", line 1012, in _refresh
  self.__read_concern))
  File "C:\Users\test\AppData\Local\Programs\Python\Python35-32\lib\site-packages
  \pymongo\cursor.py", line 850, in __send_message
  **kwargs)
  File "C:\Users\test\AppData\Local\Programs\Python\Python35-32\lib\site-packages
  \pymongo\mongo_client.py", line 827, in _send_message_with_response
  server = topology.select_server(selector)
  File "C:\Users\test\AppData\Local\Programs\Python\Python35-32\lib\site-packages
  \pymongo\topology.py", line 210, in select_server
  address))
  File "C:\Users\test\AppData\Local\Programs\Python\Python35-32\lib\site-packages
  \pymongo\topology.py", line 186, in select_servers
  self._error_message(selector))

Where should i place the database? Why there isnt any documentation for this tool? That's confusing

**Comment by anton48** [comment]
yes, python3 is necessary. and as far as I understand you need mongodb and bitcoind with full node data on the machine. 

then you may start build_cluster.py and it will crawl data from bitcoind to mongo. 

then you may start start_website.py and open http://127.0.0.1:5000 (or another ip address if it is remote machine, you need to change app.run for that) in the browser.

however, process of crawling failed in my case and web interface says "Invalid or inexistant address" when I checked several addresses.

**Comment by mathieulavoie** [comment]
@pshenmic: see https://github.com/mathieulavoie/Bitcluster/wiki/Installation-Procedure

@anton48: Building the database from scratch is a bit more complex. I did add a section into the installation procedure. Let me know if you have any question or if something doesn't work,

**Comment by anton48** [comment]
@mathieulavoie: this is exactly what I did and build_cluster.py script (step 5 of procedure "Creating the database from scratch") failed:

[/home/a48/Bitcluster]# python3.4 ./build_cluster.py 1
Block 1 crawled
Block 2 crawled
Block 3 crawled
[...]
Block 117501 crawled
Nb addr :  34076
Nb nodes :  24595
Waiting for insertion thread to complete...
DB Sync Finished
An exception will rise DB Sync Finished

nothing happens after this message for a long time and I pressed ctrl-c. At this point I stopped and was going to investigate the problem later.

**Comment by mathieulavoie** [comment]
The message shoud be "An exception will rise, press any key to see the Stacktrace". It used to be for debugging purpose during the tool development. I will remove it in the next commit.

**Comment by maciekit** [comment]
Getting his while restoring database:
$ mongorestore bitcluser_2016-07-19/
connected to: 127.0.0.1
Sat Jul 30 20:00:12.663 ERROR: don't know what to do with file [bitcluser_2016-07-19/bitcoin/addresses.metadata.json.gz]
Sat Jul 30 20:00:12.664 ERROR: don't know what to do with file [bitcluser_2016-07-19/bitcoin/addresses.bson.gz]
Sat Jul 30 20:00:12.664 ERROR: don't know what to do with file [bitcluser_2016-07-19/bitcoin/system.profile.metadata.json.gz]
Sat Jul 30 20:00:12.664 ERROR: don't know what to do with file [bitcluser_2016-07-19/bitcoin/transactions.metadata.json.gz]
Sat Jul 30 20:00:12.664 ERROR: don't know what to do with file [bitcluser_2016-07-19/bitcoin/system.profile.bson.gz]
Sat Jul 30 20:00:12.664 ERROR: don't know what to do with file [bitcluser_2016-07-19/bitcoin/transactions.bson.gz]

**Comment by mathieulavoie** [comment]
@maciekit The dump is is compressed using gzip. Use the --gzip command line option.
See https://docs.mongodb.com/manual/reference/program/mongorestore/#cmdoption--gzip

**Comment by maciekit** [comment]
@mathieulavoie: tought so, but I don't have it:
ERROR: unrecognised option '--gzip'
mongorestore version 2.4.10

**Comment by maciekit** [comment]
Ok, just answered myself, need version > 3.2.

**Comment by maciekit** [comment]
1. After reaching to last block it says

```
Block 423534 crawled
Block 423535 crawled
Block 423536 crawled
Block 423537 crawled
Block not found
```

and you have to wait for timeout to have it inserted into db. This could be avoided by checking via rpc how many blocks are there.
2. And maybe you should consider adding second parameter here:

```
$ ./build_cluster.py 
Usage: python ./build_cluster.py <starting block id> <ending block id>
```

so user can choose how big range would like to have.
