### ISSUE TITLE
Caught an error 

### ISSUE THREAD

**Issue by alextheman123** [mathieulavoie/Bitcluster#13]
Hello! I have a problem with
"Block 274900 crawled
Caught an error from Bitcoind RCP, Reconnecting and retrying...(1/10)
Block 275000 crawled" or 

Caught an error from Bitcoind RCP, Reconnecting and retrying...(1/10)
Block 270300 crawled
Caught an error from Bitcoind RCP, Reconnecting and retrying...(1/10)
Caught an error from Bitcoind RCP, Reconnecting and retrying...(2/10)
Traceback (most recent call last):
  File "build_cluster.py", line 54, in <module>
    start()
  File "build_cluster.py", line 17, in start
    while builder.crawl_block(block_id):
  File "C:\Bitcluster\crawler\base_crawler.py", line 34, in crawl_block
    block_hash = self.proxy.getblockhash(block_id)
  File "C:\Users\alexm\AppData\Local\Programs\Python\Python35-32\lib\site-packages\bitcoin\rpc.py", line 381, in getblockhash
    return lx(self._call('getblockhash', height))
  File "C:\Users\alexm\AppData\Local\Programs\Python\Python35-32\lib\site-packages\bitcoin\rpc.py", line 154, in _call
    response = self._get_response()
  File "C:\Users\alexm\AppData\Local\Programs\Python\Python35-32\lib\site-packages\bitcoin\rpc.py", line 175, in _get_response
    http_response = self.__conn.getresponse()
  File "C:\Users\alexm\AppData\Local\Programs\Python\Python35-32\lib\http\client.py", line 1197, in getresponse
    response.begin()
  File "C:\Users\alexm\AppData\Local\Programs\Python\Python35-32\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\alexm\AppData\Local\Programs\Python\Python35-32\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\alexm\AppData\Local\Programs\Python\Python35-32\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)

Creating the database from scratch
I have core i7 and 8 GB RAM

Sincerely,

**Comment by mathieulavoie** [comment]
You can restart from where it have failed for the build_cluster.py script. To improve relability, make sure that your bitcoind deamon did finish to download the full blockchain (see the debug.log file) before starting the build_cluster script. I'll change the _crawl_block_ method to add a broader exception handler.

**Comment by alextheman123** [comment]
Ok. But after that problem I downloaded Bitcoin database from your site and started mongorestore, after about 24 hours I have 3,50Gb (13%)? Is it normal?

Sincerely,
