### ISSUE TITLE
Caught an unhandled exception.

### ISSUE THREAD

**Issue by shayanb** [mathieulavoie/Bitcluster#17]
Any insights on the reason of this error? it happened while rebuilding the cluster database.
```
http.client.CannotSendRequest: Request-sent
Reconnecting and retrying...(1/10)
Caught an unhandled exception. See stacktrace:
ERROR:root:Request-sent
Traceback (most recent call last):
  File "/root/bitcluster/crawler/base_crawler.py", line 37, in crawl_block
    block_hash = self.proxy.getblockhash(block_id)
  File "/usr/local/lib/python3.5/dist-packages/bitcoin/rpc.py", line 429, in getblockhash
    return lx(self._call('getblockhash', height))
  File "/usr/local/lib/python3.5/dist-packages/bitcoin/rpc.py", line 199, in _call
    'Content-type': 'application/json'})
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1141, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.5/http/client.py", line 974, in putrequest
    raise CannotSendRequest(self.__state)
http.client.CannotSendRequest: Request-sent
Reconnecting and retrying...(1/10)
```

**Comment by mathieulavoie** [comment]
It seem to be related to issue 9 and issue 13.
